Added jenkins jobs(python)
gd-internship-abasilaia/ci-cd pull request #7
Opened 2019-02-12 10:10 UTC by BasileoLuv

2019-02-12 10:24 UTC, BasileoLuv commented
Look only python jobs. Java jobs coming soon

2019-02-13 07:09 UTC, savermyas commented on jnk/jobs/simple-java-service-master-release/config.xml
> +<?xml version='1.1' encoding='UTF-8'?>
It's a Java job

2019-02-13 07:09 UTC, savermyas commented on jnk/jobs/simple-java-service-dev-build/config.xml
> +<?xml version='1.1' encoding='UTF-8'?>
It's a Java job

2019-02-13 07:10 UTC, savermyas commented on jnk/jobs/python merge/config.xml
> +      <command>wget http://nexus:8081/repository/pypi/packages/python-calculator/0.4-SNAPSHOT/Python-Calculator-0.4-20190212.075727.tar.gz
Snapshot version is still hardcoded.

2019-02-13 07:10 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +mv dist/Python-Calculator-0.4-SNAPSHOT.tar.gz dist/Python-Calculator-0.4.tar.gz
what if you have already bumbed your version higher?

2019-02-13 07:11 UTC, savermyas requested changes
Address the comments

2019-02-18 07:40 UTC, savermyas commented on jnk/jobs/python merge/config.xml
> +          <description>tar xvzf Python-Calculator-$Package_version
Why do you need 2 parameters?

2019-02-18 07:41 UTC, savermyas commented on jnk/jobs/python merge/config.xml
> +cd Python-Calculator-0.4.1-SNAPSHOT
what if you have already released 0.4.1 and want to proceed with 0.4.2?

2019-02-18 07:41 UTC, savermyas commented on jnk/jobs/python merge/config.xml
> +git tag 0.4.1
the same as above

2019-02-18 07:42 UTC, savermyas commented on jnk/jobs/simple-python-service-dev-build/config.xml
> +      <macroTemplate>#${BUILD_NUMBER}</macroTemplate>
Commit hash info is not very informative, better to use snapshot version

2019-02-18 07:43 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +          <description>_SNAPSHOT-py2-none-any
for what?

2019-02-18 07:44 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +          <description>example: 0.4.1</description>
How will I release for example 0.4.1-20180215-12345?

2019-02-18 07:45 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +git checkout HEAD
3 checkouts in a row? for what reason?

2019-02-18 07:46 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +git commit -m &quot;information about commit&quot;
Informative

2019-02-18 07:46 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +bash artifactvers.sh
where is this script?

2019-02-18 07:47 UTC, savermyas requested changes
Updates are still needed

2019-02-21 12:49 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +cut -d= -f2 curr-snapshot.txt &gt;2.txt
Use piping for that.

2019-02-21 12:50 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +mv dist/Python_Calculator*.whl dist/Python-Calculator-$currsnapshot-py2-none-any.whl
do you really need both of them? wheel and tar.gz?

2019-02-21 12:51 UTC, savermyas commented on jnk/jobs/simple-python-service-dev-build/config.xml
> +bash script.sh</command>
what is it?

2019-02-21 12:51 UTC, savermyas commented on jnk/jobs/simple-python-service-master-release/config.xml
> +bash releaseornot.sh
what is it?

2019-02-21 12:52 UTC, savermyas commented on jnk/jobs/update version/config.xml
> +      <command>bash artifactversion.sh</command>
what is it?

2019-02-21 12:53 UTC, savermyas requested changes
Address the comments

2019-02-22 06:50 UTC, closed without merging